config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'groups/new'
    get 'groups/show'
    get 'groups/edit'
  end
# devise
  # 管理者用(URL /admin/sign_in ...)
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }
  # ユーザ用(URL /users/sign_in ...)
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# その他
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :projects, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        # 未掲載プロジェクト一覧
        get 'examination'
      end
      resources :backers, only: [:index]
      resources :participants, only: [:index]
    end
    resources :categories, only: [:index, :create, :show, :edit, :update, :destroy]
  end
  # ユーザ用
  root to: "public/homes#top"
  get "about" =>"public/homes#about"
  get "users/my_page" => "public/users#show"
  scope module: :public do
    resources :users, only: [:show, :edit, :update] do
      collection do
        # 退会確認画面
        get 'unsubscribe'
        # 論理削除用のルーティング
        patch 'withdraw'
        # 支援プロジェクト一覧表示※部分テンプレートのため実装不要→URL取得に変更
        get 'backer'
        get 'participant'
        get 'owner'
        get 'favorite'
      end
    end
    resources :projects, only: [:new, :create, :index, :show, :edit, :update] do
      resources :returns, only: [:new, :create, :index, :show, :edit, :update] do
        collection do
          get 'selects'
        end
      end
      resources :backers, only: [:new, :create, :index] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :participants, only: [:new, :create, :index, :edit, :update] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :groups, only: [:new, :create, :show, :edit, :update] do
        collection do
          get 'info'
        end
      end
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


  # namespace :admin do
  #   get 'participants/index'
  # end
  # namespace :admin do
  #   get 'backers/index'
  # end
  # namespace :admin do
  #   get 'categories/index'
  #   get 'categories/show'
  #   get 'categories/edit'
  # end
  # namespace :admin do
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'participants/new'
  #   get 'participants/log'
  #   get 'participants/complete'
  #   get 'participants/index'
  #   get 'participants/edit'
  # end
  # namespace :public do
  #   get 'backers/new'
  #   get 'backers/log'
  #   get 'backers/complete'
  #   get 'backers/index'
  # end
  # namespace :public do
  #   get 'returns/new'
  #   get 'returns/index'
  #   get 'returns/edit'
  # end
  # namespace :public do
  #   get 'projects/new'
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :public do
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

app/models/project.rb
class Project < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :category
  has_one :return
  has_many :backers, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :group

  has_one_attached :image

  # enum定義
  enum posting_status: { examination: 0, completed: 1 }
  enum area: {
    "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
  }

  # 検索機能
  def self.search(keyword)
    where(["title like? OR content like?", "%#{keyword}%", "%#{keyword}%"])
  end

  # いいね機能
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 支援機能
    # 後援者
  def backed_by?(user)
    backers.exists?(user_id: user.id)
  end
    # 参加者（参加済み）
  def parted_by?(user)
    participants.where(approval_status: "completed").exists?(user_id: user.id)
  end
    # 参加者（申請中）
  def parting_by?(user)
    participants.where(approval_status: "approval").exists?(user_id: user.id)
  end

  # バリデーション
  validates :target_amount, presence: true
  validates :end_date, presence: true
  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :content, presence: true, length: { minimum: 1, maximum: 200 }
  validates :area, presence: true
  validates :image, presence: true

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  def index
    @projects = Project.where(posting_status: "completed").page(params[:page]).per(4)
    @categories = Category.all
  end

  def examination
    @projects = Project.where(posting_status: "examination").page(params[:page]).per(4)
    @categories = Category.all
  end

  def show
    @project = Project.find(params[:id])
    @returnv = @project.return
    @backers = @project.backers.all
    @participants = @project.participants.where(approval_status: "completed")
    @total_amount = @backers.sum(:support_amount).to_i + (@project.return.p_amount * @participants.count)
    @achievement_rate = @total_amount.quo(@project.target_amount).to_f * 100
    @days_left = @project.end_date - Date.today
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    # binding.pry
    project = Project.find(params[:id])
    project.update(project_params)
    redirect_to admin_projects_path
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(:posting_status)
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/edit.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-5 text-right p-3"><h4 class="header">プロジェクト編集</h4></div>
  </div>

  <%= form_with model: @project, url: admin_project_path, method: :patch do |f| %>
    <%= render "admin/shared/error_messages", resource: @project %>

    <div class="field row d-block p-2">
      <div class="col-10 text-center"><%= f.label :◆プロジェクト掲載の承認 %></div>
    </div>

    <div class="row">
      <div class="col-3"></div>
      <div class="col-5 p-3"><h5>1.目標設定</h5></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :目標金額 %></div>
      <div class="col-5"><%= @project.target_amount %>円</div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :募集終了日 %></div>
      <div class="col-5"><%= @project.end_date %></div>
    </div>

    <div class="row">
      <div class="col-3"></div>
      <div class="col-5 p-3"><h5>2.概要</h5></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :タイトル %></div>
      <div class="col-5"><%= @project.title %></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :本文 %></div>
      <div class="col-5"><%= @project.content %></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :カテゴリ %></div>
      <div class="col-5"><%= @project.category.name %></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :地域 %></div>
      <div class="col-5"><%= @project.area %></div>
    </div>

    <div class="row">
      <div class="col-3"></div>
      <div class="col-5 p-3"><h5>3.ビジュアル</h5></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :イメージ画像 %></div>
      <div class="col-5">※詳細画面にて確認</div>
    </div>

    <div class="row">
      <div class="col-3"></div>
      <div class="col-5 p-3"><h5>4.リターン</h5></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :後援型 %></div>
      <div class="col-5"><%= @project.return.b_contents %></div>
    </div>
    <div class="row p-1">
      <div class="col-5 text-right"><%= f.label :参加型 %></div>
      <div class="col-5"><%= @project.return.p_contents %></div>
    </div>

    <div class="row">
      <div class="col-3"></div>
      <div class="col-5 p-3"><h5>4.掲載ステータス</h5></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :ステータス %></div>
      <div class="col-5">
        <%= f.radio_button :posting_status, :examination %><%= f.label :posting_status, '審査中', value: 0  %>
        <%= f.radio_button :posting_status, :completed %><%= f.label :posting_status, '審査完了', value: 1 %>
      </div>
    </div>

    <div class="field row p-3">
      <div class="col-5 text-right"><%= f.submit '保存する', class: 'btn btn-ex' %></div>
      <div class="col-1"></div>
      <div class="col-5">
        <%= link_to "削除する", admin_project_path(@project.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-ex' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/projects/examination.html.erb
<div class="container p-3">
  <!--<div class="row justify-content-center">-->
  <!--  検索枠-->
  <!--</div>-->
</div>
<div class="container">
  <div class="row justify-conte-center">
    <div class="col-2 p-1">
      <div class="card-header">カテゴリ一覧</div>
      <div class="card-body">
        <% @categories.each do |category| %>
          <p class="card-text"><%= category.name %></p>
        <% end %>
      </div>
    </div>
    <div class="col-9 p-4">
      <h4 class="header">プロジェクト一覧(未掲載)</h4>
      <div class ="wrapper grid" >
        <% @projects.each do |project| %>
          <% if project.posting_status == "examination" %>
            <div class="card text-center" style="width: 14rem; height: 13rem;">
              <%= link_to admin_project_path(project) do %>
                <div class="card-img-top pt-2">
                  <% if project.image.attached? %>
                    <%= image_tag project.image, size: "200x120" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "100x100" %>
                  <% end %>
                </div>
                <div class="card-body">
                  <h6 class="card-title text-center"><%= project.title %></h6>
                </div>
              <% end %>
              <!--<div class="card-text">現在支援金額</div>-->
              <!--<div class="card-text">支援者数</div>-->
              <!--<div class="card-text">残り</div>-->
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row justify-content-center p-4">
        <%= paginate @projects %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/index.html.erb
<div class="container p-3">
  <!--<div class="row justify-content-center">-->
  <!--  検索枠-->
  <!--</div>-->
</div>
<div class="container">
  <div class="row justify-conte-center">
    <div class="col-2 p-1">
      <div class="card-header">カテゴリ一覧</div>
      <div class="card-body">
        <% @categories.each do |category| %>
          <p class="card-text"><%= category.name %></p>
        <% end %>
      </div>
    </div>
    <div class="col-9 p-4">
      <h4 class="header">プロジェクト一覧</h4>
      <div class ="wrapper grid" >
        <% @projects.each do |project| %>
          <% if project.posting_status == "completed" %>
            <div class="card text-center" style="width: 14rem; height: 13rem;">
              <%= link_to admin_project_path(project) do %>
                <div class="card-img-top pt-2">
                  <% if project.image.attached? %>
                    <%= image_tag project.image, size: "200x120" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "100x100" %>
                  <% end %>
                </div>
                <div class="card-body">
                  <h6 class="card-title text-center"><%= project.title %></h6>
                </div>
              <% end %>
              <!--<div class="card-text">現在支援金額</div>-->
              <!--<div class="card-text">支援者数</div>-->
              <!--<div class="card-text">残り</div>-->
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row justify-content-center p-4">
        <%= paginate @projects %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/show.html.erb
<!-- Project info -->
<%= render "public/projects/info", project: @project, backers: @backers, participants: @participants,
    total_amount: @total_amount, achievement_rate: @achievement_rate, days_left: @days_left %>

<!-- Project index-->
<div class="container">
  <div class="row justify-content-center p-3">
    <div class="col-10">
      <div class="content-box">
        <p><strong>本文　　</strong><button type="button" class="btn btn-outline-info">score <%= @project.score %></button></p><br>
        <p><%= safe_join(@project.content.split("\n"),tag(:br)) %></p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center p-3">
    <div class="col-4">
      <div class="content-box">
        <p><strong>ユーザー情報</strong></p>
        <p><%= link_to admin_user_path(@project.user.id) do %>
          <%= @project.user.name %>
        <% end %></p>
        <p>　</p>
      </div>
    </div>
    <div class="col-6">
      <div class="content-box">
        <p><strong>リターン情報</strong></p>
        <p>支援者:<%= @returnv.b_contents %></p>
        <p>参加者:<%= @returnv.p_contents %></p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center p-3">
    <div class="col-3 text-center"><%= link_to "後援者一覧", admin_project_backers_path(@project), class: 'btn btn-ex' %></div>
    <div class="col-3 text-center"><%= link_to "参加者一覧", admin_project_participants_path(@project), class: 'btn btn-ex' %></div>
  </div>
</div>