config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'groups/new'
    get 'groups/show'
    get 'groups/edit'
  end
# devise
  # 管理者用(URL /admin/sign_in ...)
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }
  # ユーザ用(URL /users/sign_in ...)
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# その他
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :projects, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        # 未掲載プロジェクト一覧
        get 'examination'
      end
      resources :backers, only: [:index]
      resources :participants, only: [:index]
    end
    resources :categories, only: [:index, :create, :show, :edit, :update, :destroy]
  end
  # ユーザ用
  root to: "public/homes#top"
  get "about" =>"public/homes#about"
  get "users/my_page" => "public/users#show"
  scope module: :public do
    resources :users, only: [:show, :edit, :update] do
      collection do
        # 退会確認画面
        get 'unsubscribe'
        # 論理削除用のルーティング
        patch 'withdraw'
        # 支援プロジェクト一覧表示※部分テンプレートのため実装不要→URL取得に変更
        get 'backer'
        get 'participant'
        get 'owner'
        get 'favorite'
      end
    end
    resources :projects, only: [:new, :create, :index, :show, :edit, :update] do
      resources :returns, only: [:new, :create, :index, :show, :edit, :update] do
        collection do
          get 'selects'
        end
      end
      resources :backers, only: [:new, :create, :index] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :participants, only: [:new, :create, :index, :edit, :update] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :groups, only: [:new, :create, :show, :edit, :update] do
        collection do
          get 'info'
        end
      end
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


  # namespace :admin do
  #   get 'participants/index'
  # end
  # namespace :admin do
  #   get 'backers/index'
  # end
  # namespace :admin do
  #   get 'categories/index'
  #   get 'categories/show'
  #   get 'categories/edit'
  # end
  # namespace :admin do
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'participants/new'
  #   get 'participants/log'
  #   get 'participants/complete'
  #   get 'participants/index'
  #   get 'participants/edit'
  # end
  # namespace :public do
  #   get 'backers/new'
  #   get 'backers/log'
  #   get 'backers/complete'
  #   get 'backers/index'
  # end
  # namespace :public do
  #   get 'returns/new'
  #   get 'returns/index'
  #   get 'returns/edit'
  # end
  # namespace :public do
  #   get 'projects/new'
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :public do
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

app/models/category.rb
class Category < ApplicationRecord
  # アソシエーション
  has_many :projects, dependent: :destroy

  # バリデーション
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @category = Category.new
    @categories = Category.all.page(params[:page]).per(20)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      @categories = Category.all
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :remarks)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-5 text-right p-3"><h4 class="header">カテゴリ編集</h4></div>
  </div>
  <%= form_with model:@category, url: admin_category_path, method: :patch, local:true do |f| %>
    <%= render "admin/shared/error_messages", resource: @category %>

    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :カテゴリ名 %></div>
      <div class="col-5"><%= f.text_field :name %></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :備考 %></div>
      <div class="col-5"><%= f.text_field :remarks %></div>
    </div>
    <div class="field row p-3">
      <div class="col-5 text-right"><%= f.submit '保存する', class: 'btn btn-ex' %></div>
      <div class="col-1"></div>
      <div class="col-5">
        <%= link_to "削除する", admin_category_path(@category.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-ex'%>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-1"></div>
    <div class="col-5"><h4 class="header"> カテゴリ一覧・追加</h4></div>
  </div>

  <%= form_with model:@category, url: admin_categories_path, method: :post, local:true do |f| %>
    <%= render "admin/shared/error_messages", resource: @category %>

    <div class="row d-flex p-1">
      <div class="col-2 text-right"><%= f.label :カテゴリ名 %></div>
      <div class="col-5"><%= f.text_field :name, placeholder: "15characters"  %></div>
    </div>
    <div class="row p-1">
      <div class="col-2 text-right"><%= f.label :備考 %></div>
      <div class="col-5"><%= f.text_field :remarks %></div>
    </div>
    <div class="row p-1">
      <div class="col-2"></div>
      <div class="col-5"><%= f.submit '新規登録', class: 'btn btn-ex' %></div>
    </div>
  <% end %>

  <div class = "row mt-5">
    <div class="col-10 offset-1">
      <table class ="table table-hover table-inverse">
        <thead class = "thead-gray">
          <tr>
            <th>カテゴリ名</th>
            <th>備考</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.remarks %></td>
              <td><%= link_to "編集する", edit_admin_category_path(category.id), class: 'btn btn-ex' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-center p-4">
    <%= paginate @categories %>
  </div>
</div>