config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'groups/new'
    get 'groups/show'
    get 'groups/edit'
  end
# devise
  # 管理者用(URL /admin/sign_in ...)
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }
  # ユーザ用(URL /users/sign_in ...)
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# その他
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :projects, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        # 未掲載プロジェクト一覧
        get 'examination'
      end
      resources :backers, only: [:index]
      resources :participants, only: [:index]
    end
    resources :categories, only: [:index, :create, :show, :edit, :update, :destroy]
  end
  # ユーザ用
  root to: "public/homes#top"
  get "about" =>"public/homes#about"
  get "users/my_page" => "public/users#show"
  scope module: :public do
    resources :users, only: [:show, :edit, :update] do
      collection do
        # 退会確認画面
        get 'unsubscribe'
        # 論理削除用のルーティング
        patch 'withdraw'
        # 支援プロジェクト一覧表示※部分テンプレートのため実装不要→URL取得に変更
        get 'backer'
        get 'participant'
        get 'owner'
        get 'favorite'
      end
    end
    resources :projects, only: [:new, :create, :index, :show, :edit, :update] do
      resources :returns, only: [:new, :create, :index, :show, :edit, :update] do
        collection do
          get 'selects'
        end
      end
      resources :backers, only: [:new, :create, :index] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :participants, only: [:new, :create, :index, :edit, :update] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :groups, only: [:new, :create, :show, :edit, :update] do
        collection do
          get 'info'
        end
      end
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


  # namespace :admin do
  #   get 'participants/index'
  # end
  # namespace :admin do
  #   get 'backers/index'
  # end
  # namespace :admin do
  #   get 'categories/index'
  #   get 'categories/show'
  #   get 'categories/edit'
  # end
  # namespace :admin do
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'participants/new'
  #   get 'participants/log'
  #   get 'participants/complete'
  #   get 'participants/index'
  #   get 'participants/edit'
  # end
  # namespace :public do
  #   get 'backers/new'
  #   get 'backers/log'
  #   get 'backers/complete'
  #   get 'backers/index'
  # end
  # namespace :public do
  #   get 'returns/new'
  #   get 'returns/index'
  #   get 'returns/edit'
  # end
  # namespace :public do
  #   get 'projects/new'
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :public do
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  # アソシエーション
  has_many :projects, dependent: :destroy
  has_many :backers, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :groups, dependent: :destroy

  has_one_attached :image

  # バリデーション
  validates :name, presence: true, length: { minimum: 2, maximum: 10 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  # ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約をかける
  # is_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ゲストユーザーをさがす or 作成する
  def self.guest
    find_or_create_by!(email: 'guest@example') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    # 支援プロジェクト一覧表示(public/backerへrender)
    backers = Backer.where(user_id: @user.id).pluck(:project_id)
    @backer_projects = Project.find(backers)
    # 参加プロジェクト一覧表示(public/participantへrender)
    participant = Participant.where(user_id: @user.id).pluck(:project_id)
    @participant_projects = Project.find(participant)
    # 投稿プロジェクト一覧表示(public/ownewへrender)
    @owner_projects = Project.where(user_id: @user.id).includes(:user)
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user)
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-5 text-right p-3"><h4 class="header">ユーザ情報編集</h4></div>
  </div>
  
  <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
    <%= render "admin/shared/error_messages", resource: @user %>

    <div class="field row d-block p-2">
      <div class="col-10 text-center"><%= f.label :◆会員ステータスの更新 %></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :ユーザ名 %></div>
      <div class="col-5"><%= @user.name %></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :メールアドレス %></div>
      <div class="col-5"><%= @user.email %></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :プロフィール %></div>
      <div class="col-5"><%= @user.introduction %></div>
    </div>
    <div class="field row p-2">
      <div class="col-5 text-right"><%= f.label :会員ステータス %></div>
      <div class="col-5">
        <%= f.radio_button :is_deleted, false %><%= f.label :is_deleted, "有効", value: true %>
        <%= f.radio_button :is_deleted, true %><%= f.label :is_deleted, "退会", value: false %>
      </div>
    </div>
    <div class="field row p-2">
      <div class="col-5"></div>
      <div class="col-5"><%= f.submit "保存する", class: 'btn btn-ex' %></div>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-5 p-3"><h4 class="header">ユーザ一覧</h4></div>
  </div>
  <div class="row">
    <div class="col-10 offset-1">
      <table class="table table-hover table-inverse admin_users_table">
        <thead class="thead-gray">
          <tr>
            <th>ID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <%= link_to admin_user_path(user) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted == false %>
                有効
              <% elsif user.is_deleted == true %>
                退会
              <% end %>
            </td>
            <td><%= link_to "編集する", edit_admin_user_path(user), class: 'btn btn-ex' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center p-4">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!-- User info -->
<div class="container p-3">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-5 p-3"><h4 class="header">ユーザ情報</h4></div>
  </div>
  <div class="row p-3">
    <div class="col-4 text-center">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, size: "100×100" %>
      <% else %>
        <%= image_tag asset_path('no_image'), size: "100×100" %>
      <% end %><br>
      <%= @user.name %>
    </div>
    <div class="col-8">
      <%= @user.introduction %><br>
      <br>
      <p>会員ステータス：
        <% if @user.is_deleted == false %>
          有効
        <% elsif @user.is_deleted == true %>
          退会
        <% end %>
      </p>
      <%= link_to "編集する", edit_admin_user_path(@user), class: 'btn btn-ex' %>
    </div>
  </div>
</div>
<!-- User project -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-3 offset-1">
      <table class="table table-hover table-inverse admin_users_table">
        <thead class="thead-gray">
          <tr><th>支援プロジェクト</th></tr>
        </thead>
        <tbody>
          <% @backer_projects.each do |project| %>
            <tr>
              <td>
                <%= link_to admin_project_path(project) do %>
                  <%= project.title %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 offset-1">
      <table class="table table-hover table-inverse admin_users_table">
        <thead class="thead-gray">
          <tr><th>参加プロジェクト</th></tr>
        </thead>
        <tbody>
          <% @participant_projects.each do |project| %>
            <tr>
              <td>
                <%= link_to admin_project_path(project) do %>
                  <%= project.title %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 offset-1">
      <table class="table table-hover table-inverse admin_users_table">
        <thead class="thead-gray">
          <tr><th>投稿プロジェクト</th></tr>
        </thead>
        <tbody>
          <% @owner_projects.each do |project| %>
            <tr>
              <td>
                <%= link_to admin_project_path(project) do %>
                  <%= project.title %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
        <!--<%#= paginate @users %>-->
  </div>
</div>


<!-- render type-->

<!--<div class="container d-flex justify-content-center">-->
<!--  <div class="row">-->
<!--    <p>支援プロジェクト</p><br>-->
<!--    <%#= render "public/users/backer", backer_projects: @backer_projects %>-->
<!--  </div>-->
<!--  <div class="row">-->
<!--    <p>参加プロジェクト</p>-->
<!--    <%#= render "public/users/participant", participant_projects: @participant_projects %>-->
<!--  </div>-->
<!--  <div class="row">-->
<!--    <p>投稿プロジェクト</p>-->
<!--    <%#= render "public/users/owner", owner_projects: @owner_projects %>-->
<!--  </div>-->
<!--</div>-->