config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'groups/new'
    get 'groups/show'
    get 'groups/edit'
  end
# devise
  # 管理者用(URL /admin/sign_in ...)
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }
  # ユーザ用(URL /users/sign_in ...)
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# その他
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :projects, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        # 未掲載プロジェクト一覧
        get 'examination'
      end
      resources :backers, only: [:index]
      resources :participants, only: [:index]
    end
    resources :categories, only: [:index, :create, :show, :edit, :update, :destroy]
  end
  # ユーザ用
  root to: "public/homes#top"
  get "about" =>"public/homes#about"
  get "users/my_page" => "public/users#show"
  scope module: :public do
    resources :users, only: [:show, :edit, :update] do
      collection do
        # 退会確認画面
        get 'unsubscribe'
        # 論理削除用のルーティング
        patch 'withdraw'
        # 支援プロジェクト一覧表示※部分テンプレートのため実装不要→URL取得に変更
        get 'backer'
        get 'participant'
        get 'owner'
        get 'favorite'
      end
    end
    resources :projects, only: [:new, :create, :index, :show, :edit, :update] do
      resources :returns, only: [:new, :create, :index, :show, :edit, :update] do
        collection do
          get 'selects'
        end
      end
      resources :backers, only: [:new, :create, :index] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :participants, only: [:new, :create, :index, :edit, :update] do
        collection do
          post 'log'
          get 'complete'
        end
      end
      resources :groups, only: [:new, :create, :show, :edit, :update] do
        collection do
          get 'info'
        end
      end
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


  # namespace :admin do
  #   get 'participants/index'
  # end
  # namespace :admin do
  #   get 'backers/index'
  # end
  # namespace :admin do
  #   get 'categories/index'
  #   get 'categories/show'
  #   get 'categories/edit'
  # end
  # namespace :admin do
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'participants/new'
  #   get 'participants/log'
  #   get 'participants/complete'
  #   get 'participants/index'
  #   get 'participants/edit'
  # end
  # namespace :public do
  #   get 'backers/new'
  #   get 'backers/log'
  #   get 'backers/complete'
  #   get 'backers/index'
  # end
  # namespace :public do
  #   get 'returns/new'
  #   get 'returns/index'
  #   get 'returns/edit'
  # end
  # namespace :public do
  #   get 'projects/new'
  #   get 'projects/index'
  #   get 'projects/show'
  #   get 'projects/edit'
  # end
  # namespace :public do
  #   get 'users/show'
  #   get 'users/edit'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="logo">
      <a class="navbar-brand" href="/"><%= image_tag "logo16", width: "120%", height: "120%" %></a>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="row">
    <!-- 検索窓 -->
      <%= form_with url: search_projects_path, local: true, method: :get do |f| %>
        <div id="search-wrap">
          <!--<input type="search" value="" name="keyword" id="keyword">-->
          <%= f.text_field :keyword %>
          <!--<%#= f.submit "検索" %>-->
        </div>
      <% end %>
    </div>
    <!-- navbar -->
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if admin_signed_in? %>
          <li class="nav-item nav-link"><%= link_to "掲載済みプロジェクト", admin_projects_path, class:"link"  %></li>
          <li class="nav-item nav-link"><%= link_to "未掲載プロジェクト", examination_admin_projects_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "ユーザー", admin_users_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "カテゴリ", admin_categories_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"link" %></li>
        <% elsif user_signed_in? %>
          <li class="nav-item nav-link"><%= link_to "プロジェクトをはじめる", new_project_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "プロジェクトをさがす", projects_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "マイページ", users_my_page_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"link" %></li>
        <% else %>
          <li class="nav-item nav-link"><%= link_to "プロジェクトをはじめる", new_user_session_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "プロジェクトをさがす", projects_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "ログイン", new_user_session_path, class:"link" %></li>
          <li class="nav-item nav-link"><%= link_to "新規登録", new_user_registration_path, class:"link" %></li>
        <% end %>
      </ul>
    </div>
    <div class="login">
      <% if user_signed_in? %>
        <%= current_user.name %>
      <% end %>
    </div>
  </div>
</nav>



<!--ようこそ、<%#= current_user.name %>さん！-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Of</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Header -->
    <header>
      <%= render "layouts/header" %>
    </header>
    <!-- Main -->
    <%= yield %>
    <!-- Footer -->
    <footer class="footer py-2 border-top">
      <div class="container">
        <p class="m-0 text-center">Copyright &copy; of. 2022</p>
      </div>
    </footer>
  </body>
</html>